# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build-master:
  stage: build
  script:
    - docker build --pull -f Dockerfile.lnd -t "$CI_REGISTRY"/"$LND_IMAGE" .
    - docker push "$CI_REGISTRY"/"$LND_IMAGE"
    - docker build --pull -f Dockerfile.btcd -t "$CI_REGISTRY"/"$BTCD_IMAGE" .
    - docker push "$CI_REGISTRY"/"$BTCD_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -f Dockerfile.lnd -t "$CI_REGISTRY"/"$LND_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY"/"$LND_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build --pull -f Dockerfile.btcd -t "$CI_REGISTRY"/"$BTCD_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY"/"$BTCD_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
