# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  CI_REGISTRY_USER: "username"
  CI_REGISTRY_PASSWORD: "password"
  CI_REGISTRY: "localhost:5000"
  LND_IMAGE: "eng/lnd"
  BTCD_IMAGE: "eng/btcd"

  RANCHER_COMPOSE_DOWNLOAD: "https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz"
  RANCHER_COMPOSE_TAR: "rancher-compose-linux-amd64-v0.12.5.tar.gz"
  RANCHER_COMPOSE_DIR: "rancher-compose-v0.12.5"
  STACK_NAME: "sample-lnd-cluster"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build
  - publish
  - deploy


build-master:
  stage: build
  script:
    - docker build --pull -f Dockerfile.lnd -t "$CI_REGISTRY"/"$LND_IMAGE" .
    - docker build --pull -f Dockerfile.btcd -t "$CI_REGISTRY"/"$BTCD_IMAGE" .
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -f Dockerfile.lnd -t "$CI_REGISTRY"/"$LND_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker build --pull -f Dockerfile.btcd -t "$CI_REGISTRY"/"$BTCD_IMAGE:$CI_COMMIT_REF_SLUG" .
  except:
    - master

publish-master:
  stage: publish
  script:
    - docker push "$CI_REGISTRY"/"$LND_IMAGE"
    - docker push "$CI_REGISTRY"/"$BTCD_IMAGE"
  only:
    - master
    
publish-develop:
  stage: publish
  script:
    - docker push "$CI_REGISTRY"/"$LND_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY"/"$BTCD_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - develop