FROM golang:1.13-alpine as builder

ENV GODEBUG netdns=cgo

RUN apk add --no-cache --update alpine-sdk \
    git \
    make

RUN go get -d github.com/lightningnetwork/lnd
WORKDIR $GOPATH/src/github.com/lightningnetwork/lnd
RUN make \
&&  make install tags="signrpc walletrpc chainrpc invoicesrpc routerrpc"

FROM alpine as final

EXPOSE 9735 10009

COPY --from=builder /go/bin/lncli /bin/
COPY --from=builder /go/bin/lnd /bin/

RUN apk add --no-cache \
    bash