version: "2"

services:
  btcd:
    image: ${CI_REGISTRY}eng/btcd
    container_name: btcd
    hostname: btcd
    volumes:
      - shared:/rpc
    entrypoint: btcd --txindex --simnet --rpcuser=kek --rpcpass=kek --rpccert=/rpc/rpc.cert --rpckey=/rpc/rpc.key --debuglevel=info --rpclisten=0.0.0.0 --miningaddr=${MINING_ADDRESS}

  alice:
    image: ${CI_REGISTRY}eng/lnd
    container_name: alice
    hostname: alice
    volumes:
      - shared:/rpc
    entrypoint: lnd --debuglevel=info --bitcoin.simnet --bitcoin.active --bitcoin.node=btcd --btcd.rpcuser=kek --btcd.rpcpass=kek --btcd.rpccert=/rpc/rpc.cert --btcd.rpchost=btcd

  bob:
    image: ${CI_REGISTRY}eng/lnd
    container_name: bob
    hostname: bob
    volumes:
      - shared:/rpc
    entrypoint: lnd --debuglevel=info --bitcoin.simnet --bitcoin.active --bitcoin.node=btcd --btcd.rpcuser=kek --btcd.rpcpass=kek --btcd.rpccert=/rpc/rpc.cert --btcd.rpchost=btcd

volumes:
  shared:
    driver: local
