version: "2.2"

services:
  bitcoin:
    image: tutorial/bitcoind
    restart: always
    volumes:
      - ./data/bitcoind/blockdata:/var/lib/bitcoin
      - ./data/bitcoind/conf:/etc/bitcoin
    ports:
      - "8333:8333"

  lnd:
    image: tutorial/lnd
    restart: always
    volumes:
      - ./data/lnd:/root/.lnd
    ports:
      - "8080:8080"
      - "9735:9735"